#!/bin/bash

set -euo pipefail

DECODER="./pa-wsprcan/k9an-wsprd"
SOURCE_PATTERN="${1:-USB}"

decode() {
	./set-usb-mic-source.sh "$SOURCE_PATTERN"
	"$DECODER"
}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')

	if ((10#$min % 2 == 0 && 10#$sec == 0)); then
		echo -n "Executing wspr_decode "
		date
		decode
	elif ((10#$sec < 49)); then
		sleep 10
	else
		sleep 1
	fi
done
